In [1]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans

In [2]:
Hostname = "13.250.191.87:3306"  
username = 'dm_team'
userpwd = 'dm_team123#'
dbname = "project_itsm"

In [3]:
conn = create_engine('mysql+pymysql://'+username+':'+userpwd+'@'+Hostname+'/'+dbname)

In [4]:
query = "select * from dataset_list" 

In [5]:
data = pd.read_sql(query,conn)

In [6]:
data.shape

(46606, 25)

In [7]:
print((data[['CI_Name', 'CI_Cat', 'CI_Subcat', 'WBS', 'Incident_ID', 'Status',
       'Impact', 'Urgency', 'Priority', 'number_cnt', 'Category', 'KB_number',
       'Alert_Status', 'No_of_Reassignments', 'Open_Time', 'Reopen_Time',
       'Resolved_Time', 'Close_Time', 'Handle_Time_hrs', 'Closure_Code',
       'No_of_Related_Interactions', 'Related_Interaction',
       'No_of_Related_Incidents', 'No_of_Related_Changes', 'Related_Change']
      ] == "NA").sum())

CI_Name                          0
CI_Cat                           0
CI_Subcat                        0
WBS                              0
Incident_ID                      0
Status                           0
Impact                           0
Urgency                          0
Priority                      1380
number_cnt                       0
Category                         0
KB_number                        0
Alert_Status                     0
No_of_Reassignments              0
Open_Time                        0
Reopen_Time                      0
Resolved_Time                    0
Close_Time                       0
Handle_Time_hrs                  0
Closure_Code                     0
No_of_Related_Interactions       0
Related_Interaction              0
No_of_Related_Incidents          0
No_of_Related_Changes            0
Related_Change                   0
dtype: int64


In [8]:
data.replace("NA",np.NAN,inplace = True)
data.head()
data.shape

(46606, 25)

In [9]:
data.dropna(inplace = True)
data.shape


(45226, 25)

In [10]:
enc = LabelEncoder()

In [11]:
data.CI_Name = enc.fit_transform(data.CI_Name)
data.CI_Cat = enc.fit_transform(data.CI_Cat)
data.CI_Subcat=enc.fit_transform(data.CI_Subcat)
data.WBS=enc.fit_transform(data.WBS)
data.Incident_ID=enc.fit_transform(data.Incident_ID)
data.Status=enc.fit_transform(data.Status)
data.Impact=enc.fit_transform(data.Impact)
data.Urgency=enc.fit_transform(data.Urgency)
data.Priority=enc.fit_transform(data.Priority)
data.number_cnt=enc.fit_transform(data.number_cnt)
data.Reopen_Time=enc.fit_transform(data.Reopen_Time)
data.Resolved_Time=enc.fit_transform(data.Resolved_Time)
data.Close_Time=enc.fit_transform(data.Close_Time)
data.Handle_Time_hrs=enc.fit_transform(data.Handle_Time_hrs)
data.Closure_Code=enc.fit_transform(data.Closure_Code)
data.No_of_Related_Interactions=enc.fit_transform(data.No_of_Related_Interactions)
data.Related_Interaction=enc.fit_transform(data.Related_Interaction)
data.No_of_Related_Incidents=enc.fit_transform(data.No_of_Related_Incidents)
data.No_of_Related_Changes=enc.fit_transform(data.No_of_Related_Changes)
data.Related_Change=enc.fit_transform(data.Related_Change)

In [12]:
data.head()

CI_Name  CI_Cat  CI_Subcat  WBS  Incident_ID  Status  Impact  Urgency  \
0     2670      12         56  136            0       0       3        3   
1     2786       2         56   70            1       0       2        2   
3     2786       2         56   70            2       0       3        3   
4     2786       2         56   70            3       0       3        3   
5     2786       2         56   70            4       0       3        3   

   Priority  number_cnt       ...       Reopen_Time Resolved_Time Close_Time  \
0         3       27192       ...                 0          3448       3564   
1         2       18742       ...                74          1152       1188   
3         3       29108       ...                 0         15062      15512   
4         3       15612       ...                 0          8239       8497   
5         3         283       ...                 0          8238       8496   

  Handle_Time_hrs Closure_Code  No_of_Related_Interactions  \
0           19641            7                           1   
1           21157           11                           1   
3           21072            6                           1   
4           18117            7                           1   
5           18114            7                           1   

   Related_Interaction  No_of_Related_Incidents  No_of_Related_Changes  \
0                    2                       10                      0   
1                    3                        1                      0   
3                    4                        0                      0   
4                    5                        0                      0   
5                    6                        0                      0   

   Related_Change  
0               0  
1               0  
3               0  
4               0  
5               0  

[5 rows x 25 columns]

In [13]:
data.corr(method='pearson',min_periods= 1) #finding correlation

CI_Name    CI_Cat  CI_Subcat       WBS  \
CI_Name                     1.000000  0.174577   0.950508 -0.107383   
CI_Cat                      0.174577  1.000000   0.205651 -0.226934   
CI_Subcat                   0.950508  0.205651   1.000000 -0.122873   
WBS                        -0.107383 -0.226934  -0.122873  1.000000   
Incident_ID                 0.021126  0.033984   0.034986  0.001903   
Status                     -0.033252 -0.000518  -0.031304  0.002971   
Impact                      0.102190 -0.055927   0.073337  0.038565   
Urgency                     0.113127 -0.059515   0.086935  0.031123   
Priority                    0.109441 -0.053666   0.082255  0.035011   
number_cnt                 -0.004806  0.001946  -0.004998  0.005717   
Reopen_Time                 0.011070 -0.018355   0.013969  0.003137   
Resolved_Time               0.059512  0.016069   0.054371  0.004997   
Close_Time                  0.008899  0.008794   0.009310  0.006075   
Handle_Time_hrs            -0.046145 -0.072676  -0.053765  0.078277   
Closure_Code                0.126876 -0.035704   0.153100 -0.067922   
No_of_Related_Interactions -0.018536 -0.023268  -0.016622 -0.007979   
Related_Interaction         0.027504  0.036628   0.038793  0.007818   
No_of_Related_Incidents     0.012167 -0.019300   0.010639  0.019970   
No_of_Related_Changes       0.010821  0.001431   0.013704 -0.014646   
Related_Change             -0.021085 -0.003387  -0.016200  0.002926   

                            Incident_ID    Status    Impact   Urgency  \
CI_Name                        0.021126 -0.033252  0.102190  0.113127   
CI_Cat                         0.033984 -0.000518 -0.055927 -0.059515   
CI_Subcat                      0.034986 -0.031304  0.073337  0.086935   
WBS                            0.001903  0.002971  0.038565  0.031123   
Incident_ID                    1.000000 -0.016644 -0.030076 -0.034053   
Status                        -0.016644  1.000000 -0.023071 -0.023096   
Impact                        -0.030076 -0.023071  1.000000  0.980080   
Urgency                       -0.034053 -0.023096  0.980080  1.000000   
Priority                      -0.029720 -0.022918  0.991755  0.989807   
number_cnt                     0.006072  0.005129 -0.000300 -0.000518   
Reopen_Time                   -0.028592 -0.002615  0.038190  0.037093   
Resolved_Time                  0.166853  0.007585  0.062351  0.061181   
Close_Time                     0.179279  0.007031  0.003630  0.001701   
Handle_Time_hrs               -0.071691  0.002930  0.090690  0.090145   
Closure_Code                   0.010385 -0.003823 -0.047500 -0.046800   
No_of_Related_Interactions    -0.046130 -0.003416 -0.006973 -0.008145   
Related_Interaction            0.884852 -0.014117 -0.027387 -0.030192   
No_of_Related_Incidents        0.012272 -0.001074 -0.066357 -0.066959   
No_of_Related_Changes         -0.024454 -0.001399 -0.042786 -0.043546   
Related_Change                 0.027315 -0.001208 -0.047690 -0.048349   

                            Priority  number_cnt  Reopen_Time  Resolved_Time  \
CI_Name                     0.109441   -0.004806     0.011070       0.059512   
CI_Cat                     -0.053666    0.001946    -0.018355       0.016069   
CI_Subcat                   0.082255   -0.004998     0.013969       0.054371   
WBS                         0.035011    0.005717     0.003137       0.004997   
Incident_ID                -0.029720    0.006072    -0.028592       0.166853   
Status                     -0.022918    0.005129    -0.002615       0.007585   
Impact                      0.991755   -0.000300     0.038190       0.062351   
Urgency                     0.989807   -0.000518     0.037093       0.061181   
Priority                    1.000000   -0.000814     0.038017       0.062698   
number_cnt                 -0.000814    1.000000     0.008181       0.004834   
Reopen_Time                 0.038017    0.008181     1.000000       0.069856   
Resolved_Time               0.062698    0.0

In [14]:
X = data.loc[:,['Impact','Status','No_of_Related_Incidents','Urgency']]

In [15]:
Y = data.Priority

In [16]:
model = DecisionTreeClassifier(max_depth= 4)

In [17]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size = 0.4 , random_state = 10)

In [18]:
model.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [19]:
Y_predict = model.predict(X_test)

In [20]:
print(classification_report(Y_test,Y_predict))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         1
          1       1.00      0.99      1.00       302
          2       1.00      1.00      1.00      2117
          3       1.00      1.00      1.00      9076
          4       1.00      1.00      1.00      6595

avg / total       1.00      1.00      1.00     18091



In [21]:
print(confusion_matrix(Y_test,Y_predict))

[[   1    0    0    0    0]
 [   0  300    2    0    0]
 [   0    0 2117    0    0]
 [   0    0    0 9076    0]
 [   0    0    0    0 6595]]


In [22]:
print(accuracy_score(Y_test,Y_predict))

0.9998894477917196


In [23]:
model1 = LinearRegression()

In [24]:
model1.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [25]:
Y_predict = model1.predict(X_test)

In [26]:
Y_predict

array([2.99100752, 2.99100752, 3.99177852, ..., 2.99100752, 2.99100752,
       2.99100752])

In [27]:
print(r2_score(Y_test,Y_predict)) #accuracy is classification metrics regression cant use it

0.9920666408246916


In [28]:
list1 = []
range = np.arange(1,26)
X_train1,X_test1,Y_train1,Y_test1 = train_test_split(X,Y,test_size = 0.3 , random_state = 1)
for k in range:
    model2 = KNeighborsClassifier(n_neighbors= k)
    model2.fit(X_train1,Y_train1)
    Y_predict = model2.predict(X_test1)
    list1.append(accuracy_score(Y_test1,Y_predict))
list1

[0.9996314858490566,
 0.9995577830188679,
 0.9994840801886793,
 0.9995577830188679,
 0.9995577830188679,
 0.9994840801886793,
 0.9994840801886793,
 0.9994840801886793,
 0.9994840801886793,
 0.9992629716981132,
 0.9991155660377359,
 0.9991892688679245,
 0.9988207547169812,
 0.9980837264150944,
 0.9979363207547169,
 0.9983048349056604,
 0.9980100235849056,
 0.9980100235849056,
 0.9980837264150944,
 0.9980837264150944,
 0.9980837264150944,
 0.9980100235849056,
 0.9979363207547169,
 0.9976415094339622,
 0.9975678066037735]

In [29]:
model2.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=25, p=2,
           weights='uniform')

In [30]:
Y_predict = model2.predict(X_test)

In [31]:
print(classification_report(Y_test,Y_predict),confusion_matrix(Y_test,Y_predict))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00         1
          1       0.99      0.98      0.99       302
          2       1.00      1.00      1.00      2117
          3       1.00      1.00      1.00      9076
          4       1.00      1.00      1.00      6595

avg / total       1.00      1.00      1.00     18091
 [[   0    1    0    0    0]
 [   0  296    2    4    0]
 [   0    1 2107    6    3]
 [   0    0    6 9067    3]
 [   0    0    0    5 6590]]


D:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [32]:
print(accuracy_score(Y_test,Y_predict))

0.9982864407716544
