In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,scale
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("G://project.csv")

D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [43]:
data.iloc[:,9:26]

Priority  number_cnt                 Category  KB_number Alert_Status  \
0             3    0.601292                 incident  KM0000553       closed   
1             2    0.415050                 incident  KM0000611       closed   
2             4    0.517551  request for information  KM0000339       closed   
3             3    0.642927                 incident  KM0000611       closed   
4             3    0.345258                 incident  KM0000611       closed   
5             3    0.006676                 incident  KM0000611       closed   
6             3    0.192907                 incident  KM0000401       closed   
7             3    0.996468                 incident  KM0000611       closed   
8             4    0.269574                 incident  KM0000611       closed   
9             3    0.306670                 incident  KM0000401       closed   
10            3    0.439909                 incident  KM0000611       closed   
11            3    0.291928                 incident  KM0000611       closed   
12            3    0.776486                 incident  KM0000401       closed   
13            3    0.592713                 incident  KM0000611       closed   
14            2    0.025310                 incident  KM0000670       closed   
15            3    0.701705                 incident  KM0000401       closed   
16            3    0.440613                 incident  KM0000852       closed   
17            3    0.151630                 incident  KM0000928       closed   
18            2    0.860255                 incident  KM0001430       closed   
19            5    0.663615                 incident  KM0000401       closed   
20            3    0.428148                 incident  KM0000611       closed   
21            3    0.070123                 incident  KM0000579       closed   
22            3    0.529581                 incident  KM0000611       closed   
23            3    0.898982                 incident  KM0000611       closed   
24            3    0.146862                 incident  KM0000928       closed   
25            3    0.941495                 incident  KM0000931       closed   
26            3    0.076103                 incident  KM0000401       closed   
27            5    0.748361  request for information  KM0000524       closed   
28            5    0.246183  request for information  KM0000592       closed   
29            5    0.853722  request for information  KM0001104       closed   
...         ...         ...                      ...        ...          ...   
46576         3    0.034391                 incident  KM0001080       closed   
46577         3    0.914837                 incident  KM0001106       closed   
46578         3    0.418911                 incident  KM0001080       closed   
46579         3    0.957322                 incident  KM0001828       closed   
46580         5    0.616431  request for information  KM0000656       closed   
46581         5    0.494802  request for information  KM0000225       closed   
46582         3    0.063762                 incident  KM0001859       closed   
46583         3    0.607836                 incident  KM0001058       closed   
46584         3    0.307157                 incident  KM0002042       closed   
46585         2    0.921967                 incident  KM0000182       closed   
46586         3    0.221723                 incident  KM0001080       closed   
46587         3    0.107287                 incident  KM0002102       closed   
46588         5    0.880442  request for information  KM0000225       closed   
46589         3    0.924862                 incident  KM0002102       closed   
46590         4    0.767070                 incident  KM0000940       closed   
46591         3    0.174233                 incident  KM0002305       closed   
46592         2    0.464394                 incident  KM0000204       closed   
46593         3    0.387275                 incident  KM0001607       closed   
46594  

In [4]:
#data[("No_of_Related_Incidents")].fillna(value = 0, inplace = True)
#for column in data:
#    data.fillna(value = 0 ,inplace = True)
#data.head()
        

In [5]:
data.Impact = data['Impact'].astype('str')
data.Urgency = data['Urgency'].astype('str')

In [6]:
data[data.Impact.str.contains('NS') == True]
data[data.Urgency.str.contains('NA') == True]

Empty DataFrame
Columns: [Unnamed: 0, CI_Name, CI_Cat, CI_Subcat, WBS, Incident_ID, Status, Impact, Urgency, Priority, number_cnt, Category, KB_number, Alert_Status, No_of_Reassignments, Open_Time, Reopen_Time, Resolved_Time, Close_Time, Handle_Time_hrs, Closure_Code, No_of_Related_Interactions, Related_Interaction, No_of_Related_Incidents, No_of_Related_Changes, Related_Change]
Index: []

[0 rows x 26 columns]

In [7]:
data[data.Urgency.str.contains(' ')==True]

Unnamed: 0    CI_Name       CI_Cat                 CI_Subcat  \
38305       38305  SBA000743  application  Server Based Application   

             WBS Incident_ID  Status Impact       Urgency  Priority  \
38305  WBS000076   IM0038625  Closed      5  5 - Very Low       5.0   

           ...        Reopen_Time     Resolved_Time        Close_Time  \
38305      ...                NaN  20-02-2014 15:57  20-02-2014 15:57   

      Handle_Time_hrs                  Closure_Code  \
38305     0,089166667  No error - works as designed   

      No_of_Related_Interactions Related_Interaction No_of_Related_Incidents  \
38305                        1.0           SD0117519                     NaN   

      No_of_Related_Changes Related_Change  
38305                   NaN            NaN  

[1 rows x 26 columns]

In [8]:
data.drop(data.index[[38305]],inplace=True)

In [9]:
data[38300:38310]

Unnamed: 0    CI_Name          CI_Cat                 CI_Subcat  \
38300       38300  SBA000033     application  Server Based Application   
38301       38301  SUB000456  subapplication     Web Based Application   
38302       38302  SUB000456  subapplication     Web Based Application   
38303       38303  WBA000133     application     Web Based Application   
38304       38304  SBA000689     application  Server Based Application   
38306       38306  WBA000133     application     Web Based Application   
38307       38307  WBA000058     application     Web Based Application   
38308       38308  WBA000058     application     Web Based Application   
38309       38309  SUB000424  subapplication     Web Based Application   
38310       38310  SBA000462     application  Server Based Application   

             WBS Incident_ID  Status Impact Urgency  Priority      ...        \
38300  WBS000086   IM0038620  Closed      4       4       4.0      ...         
38301  WBS000073   IM0038621  Closed      4       4       4.0      ...         
38302  WBS000073   IM0038622  Closed      4       4       4.0      ...         
38303  WBS000073   IM0038623  Closed      4       4       4.0      ...         
38304  WBS000228   IM0038624  Closed      5       5       5.0      ...         
38306  WBS000073   IM0038626  Closed      5       5       5.0      ...         
38307  WBS000073   IM0038627  Closed      4       4       4.0      ...         
38308  WBS000073   IM0038628  Closed      4       4       4.0      ...         
38309  WBS000073   IM0038629  Closed      5       5       5.0      ...         
38310  WBS000073   IM0038630  Closed      4       4       4.0      ...         

            Reopen_Time     Resolved_Time        Close_Time Handle_Time_hrs  \
38300               NaN  03-03-2014 09:19  03-03-2014 09:19  3,02,21,38,889   
38301               NaN  20-02-2014 16:23  20-02-2014 16:23     0,723333333   
38302               NaN  20-02-2014 15:56  20-02-2014 15:56     0,164722222   
38303  24-02-2014 12:56  26-02-2014 08:31  26-02-2014 08:31  1,46,36,11,111   
38304               NaN  20-02-2014 16:06  20-02-2014 16:07     0,325555556   
38306               NaN  20-02-2014 16:30  20-02-2014 16:30     0,513611111   
38307               NaN  20-02-2014 16:25  20-02-2014 16:25     0,309722222   
38308               NaN  20-02-2014 16:24  20-02-2014 16:24     0,294444444   
38309               NaN  21-02-2014 09:58  21-02-2014 09:58  4,34,02,77,778   
38310               NaN  20-02-2014 16:43  20-02-2014 16:43     0,238888889   

                       Closure_Code No_of_Related_Interactions  \
38300                         Other                        2.0   
38301                      Software                        1.0   
38302                      Software                        1.0   
38303          User manual not used                        3.0   
38304  No error - works as designed                        1.0   
38306                      Software                        1.0   
38307                      Software                        1.0   
38308                      Software                        1.0   
38309                      Software                        1.0   
38310                      Software                        1.0   

      Related_Interaction No_of_Related_Incidents No_of_Related_Changes  \
38300         #MULTIVALUE                     NaN                   NaN   
38301           SD0117513                     NaN                   NaN   
38302           SD0117511                     NaN                   NaN   
38303         #MULTIVALUE                     NaN                   NaN   
38304           SD0117516                     NaN                   NaN   
38306           SD0117521                     NaN                   NaN   
38307           SD0117527                     NaN                   NaN   
38308           SD0117523                     NaN                   NaN   
38309           SD0117524              

In [10]:
data = data.replace('NS',np.nan)
data = data.replace('NA',np.nan)

In [11]:
data.head()

Unnamed: 0    CI_Name          CI_Cat              CI_Subcat        WBS  \
0           0  SUB000508  subapplication  Web Based Application  WBS000162   
1           1  WBA000124     application  Web Based Application  WBS000088   
2           2  DTA000024     application    Desktop Application  WBS000092   
3           3  WBA000124     application  Web Based Application  WBS000088   
4           4  WBA000124     application  Web Based Application  WBS000088   

  Incident_ID  Status Impact Urgency  Priority      ...        \
0   IM0000004  Closed      4       4       4.0      ...         
1   IM0000005  Closed      3       3       3.0      ...         
2   IM0000006  Closed    NaN       3       NaN      ...         
3   IM0000011  Closed      4       4       4.0      ...         
4   IM0000012  Closed      4       4       4.0      ...         

        Reopen_Time     Resolved_Time        Close_Time Handle_Time_hrs  \
0               NaN  04-11-2013 13:50  04-11-2013 13:51  3,87,16,91,111   
1  02-12-2013 12:31  02-12-2013 12:36  02-12-2013 12:36  4,35,47,86,389   
2               NaN  13-01-2014 15:12  13-01-2014 15:13  4,84,31,19,444   
3               NaN  14-11-2013 09:31  14-11-2013 09:31  4,32,18,33,333   
4               NaN  08-11-2013 13:55  08-11-2013 13:55  3,38,39,03,333   

                   Closure_Code No_of_Related_Interactions  \
0                         Other                        1.0   
1                      Software                        1.0   
2  No error - works as designed                        1.0   
3                Operator error                        1.0   
4                         Other                        1.0   

  Related_Interaction No_of_Related_Incidents No_of_Related_Changes  \
0           SD0000007                     2.0                   NaN   
1           SD0000011                     1.0                   NaN   
2           SD0000017                     NaN                   NaN   
3           SD0000025                     NaN                   NaN   
4           SD0000029                     NaN                   NaN   

  Related_Change  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  

[5 rows x 26 columns]

In [19]:
data = data.fillna(method = 'ffill')

In [20]:
data.head()

Unnamed: 0    CI_Name          CI_Cat              CI_Subcat        WBS  \
0           0  SUB000508  subapplication  Web Based Application  WBS000162   
1           1  WBA000124     application  Web Based Application  WBS000088   
2           2  DTA000024     application    Desktop Application  WBS000092   
3           3  WBA000124     application  Web Based Application  WBS000088   
4           4  WBA000124     application  Web Based Application  WBS000088   

  Incident_ID  Status Impact Urgency  Priority      ...        \
0   IM0000004  Closed      4       4  4.000000      ...         
1   IM0000005  Closed      3       3  3.000000      ...         
2   IM0000006  Closed      3       3  4.215788      ...         
3   IM0000011  Closed      4       4  4.000000      ...         
4   IM0000012  Closed      4       4  4.000000      ...         

        Reopen_Time     Resolved_Time        Close_Time Handle_Time_hrs  \
0               NaN  04-11-2013 13:50  04-11-2013 13:51  3,87,16,91,111   
1  02-12-2013 12:31  02-12-2013 12:36  02-12-2013 12:36  4,35,47,86,389   
2  02-12-2013 12:31  13-01-2014 15:12  13-01-2014 15:13  4,84,31,19,444   
3  02-12-2013 12:31  14-11-2013 09:31  14-11-2013 09:31  4,32,18,33,333   
4  02-12-2013 12:31  08-11-2013 13:55  08-11-2013 13:55  3,38,39,03,333   

                   Closure_Code No_of_Related_Interactions  \
0                         Other                        1.0   
1                      Software                        1.0   
2  No error - works as designed                        1.0   
3                Operator error                        1.0   
4                         Other                        1.0   

  Related_Interaction No_of_Related_Incidents No_of_Related_Changes  \
0           SD0000007                2.000000              1.058929   
1           SD0000011                1.000000              1.058929   
2           SD0000017                1.669394              1.058929   
3           SD0000025                1.669394              1.058929   
4           SD0000029                1.669394              1.058929   

  Related_Change  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  

[5 rows x 26 columns]

In [21]:
data.Impact = data['Impact'].astype('int')

In [22]:
data.Urgency = data['Urgency'].astype('int')

In [23]:
enc = LabelEncoder()

In [24]:
data.Impact = enc.fit_transform(data.Impact)
data.Urgency = enc.fit_transform(data.Urgency)
#data.No_of_Related_Incidents = enc.fit_transform(data.No_of_Related_Incidents)
data.Priority = enc.fit_transform(data.Priority)



In [25]:
X = data.loc[:,['Impact','No_of_Related_Incidents']]
Y = data.Priority

In [26]:
#Importing KNN model
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors= 3)

In [27]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size = 0.3 ,random_state = 15)

In [28]:
model.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [29]:
Y_predict = model.predict(X_test)

In [30]:
Y_predict

array([5, 3, 3, ..., 3, 3, 3], dtype=int64)

In [31]:
#Importing Preprocessing
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [32]:
print(confusion_matrix(Y_test,Y_predict),classification_report(Y_test,Y_predict))

[[   0    1    0    0    0    0]
 [   2  201    4    0    0    0]
 [   0    1 1560   34    0    1]
 [   0    2    4 6737    0   59]
 [   0    8   80  199    0  161]
 [   1    0    0    0    0 4927]]              precision    recall  f1-score   support

          0       0.00      0.00      0.00         1
          1       0.94      0.97      0.96       207
          2       0.95      0.98      0.96      1596
          3       0.97      0.99      0.98      6802
          4       0.00      0.00      0.00       448
          5       0.96      1.00      0.98      4928

avg / total       0.93      0.96      0.94     13982



D:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [33]:
print(accuracy_score(Y_test,Y_predict))

0.9601630668001716


In [34]:
#Importing KNN model
from sklearn.linear_model import LogisticRegression

In [35]:
model_LR = LogisticRegression() 

In [36]:
model_LR.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [37]:
Y_predict = model_LR.predict(X_test)

In [38]:
Y_predict

array([5, 3, 3, ..., 3, 3, 3], dtype=int64)

In [39]:
accuracy_score(Y_test,Y_predict)

0.8348591045630096

In [40]:
import matplotlib.pyplot as plt